import type { SavedProductListPage, SavedProductView } from "@/lib/product-types";

const now = "2026-05-09T12:00:00.000Z";

export const MOCK_SAVED_PRODUCT: SavedProductView = {
  id: 1,
  displayName: "프로쉬 식기세척기 주방세제 그린레몬 미니 50개입",
  refinedName: "프로쉬 식기세척기 주방세제 그린레몬 미니 50개입",
  brand: "프로쉬",
  summary: "식기세척기 전용 미니 캡슐형 세제로, 그린레몬 향과 50개입 구성이 핵심입니다.",
  analysisStatus: "MOCK_READY",
  sameKeywords: [
    "프로쉬 식기세척기 주방세제 그린레몬 미니 50개입",
    "프로쉬 식기세척기 세제 그린레몬 미니 캡슐 50개입",
  ],
  relatedKeywords: ["식기세척기 주방세제 미니 캡슐 50개입", "식기세척기 세제 미니 캡슐 50개입"],
  relatedCoreAttributes: ["식기세척기 주방세제", "미니 캡슐", "50개입", "그린레몬 향"],
  sourceProduct: {
    id: 97,
    marketName: "kurly",
    marketProductNo: "1000861713",
    sourceUrl: "https://www.kurly.com/goods/1000861713",
    name: "[프로쉬] 식기세척기 주방세제 그린레몬 미니 50개입",
    imageUrl:
      "https://3p-image.kurly.com/files/abd16f31-25d6-49f5-9ecf-5682e8defc2b/10f8e5f9-cd51-468b-a65c-10bb375e177b.jpg",
    price: 16900,
  },
  sameProductLinks: [
    {
      id: 1001,
      marketName: "danawa",
      marketProductNo: "mock-catalog-1000861713",
      marketItemNo: null,
      mallCode: null,
      mallName: null,
      linkType: "DANAWA_CATALOG",
      relationKind: "SAME_PRODUCT",
      searchKeyword: "프로쉬 식기세척기 주방세제 그린레몬 미니 50개입",
      sourceUrl: "https://search.danawa.com/dsearch.php?query=프로쉬 식기세척기 주방세제",
      name: "프로쉬 식기세척기 주방세제 그린레몬 미니 50개입",
      imageUrl:
        "https://3p-image.kurly.com/files/abd16f31-25d6-49f5-9ecf-5682e8defc2b/10f8e5f9-cd51-468b-a65c-10bb375e177b.jpg",
      price: 15900,
      isCatalog: true,
      categoryName: "주방세제/세정제",
      mallCount: 12,
      reviewCount: 128,
      rating: 4.7,
      summary: "그린레몬향, 미니 캡슐형, 식기세척기 전용",
      recommendationScore: null,
      recommendationTier: null,
      recommendationReasons: [],
      listingOrder: 1,
      isAd: false,
      offers: [
        {
          id: 2001,
          marketName: "coupang",
          marketProductNo: "mock-coupang-1000861713",
          marketItemNo: null,
          mallName: "쿠팡",
          sellerName: "로켓배송",
          sourceUrl: "https://www.coupang.com/",
          name: "프로쉬 식기세척기 세제 그린레몬 미니 50개입",
          imageUrl: null,
          price: 15900,
          shippingFee: 0,
          finalPrice: 15900,
          deliveryText: "무료배송",
          availability: "판매중",
          listingOrder: 1,
          isAd: false,
        },
        {
          id: 2002,
          marketName: "gmarket",
          marketProductNo: "mock-gmarket-1000861713",
          marketItemNo: null,
          mallName: "G마켓",
          sellerName: "공식 판매처",
          sourceUrl: "https://www.gmarket.co.kr/",
          name: "프로쉬 그린레몬 미니 식기세척기 세제 50개입",
          imageUrl: null,
          price: 14900,
          shippingFee: 3000,
          finalPrice: 17900,
          deliveryText: "배송비 3,000원",
          availability: "판매중",
          listingOrder: 2,
          isAd: false,
        },
      ],
    },
    {
      id: 1002,
      marketName: "danawa",
      marketProductNo: "mock-ad-1000861713",
      marketItemNo: null,
      mallCode: "mock-mall",
      mallName: "다나와 광고몰",
      linkType: "DANAWA_AD_CATALOG",
      relationKind: "SAME_PRODUCT",
      searchKeyword: "프로쉬 식기세척기 세제 미니 50개입",
      sourceUrl: "https://search.danawa.com/dsearch.php?query=프로쉬 식기세척기 세제 미니",
      name: "프로쉬 식기세척기 세제 미니 50개입 광고 후보",
      imageUrl: null,
      price: 16800,
      isCatalog: true,
      categoryName: "식기세척기 세제",
      mallCount: 8,
      reviewCount: 42,
      rating: 4.5,
      summary: "미니 태블릿형 식기세척기 세제",
      recommendationScore: null,
      recommendationTier: null,
      recommendationReasons: [],
      listingOrder: 2,
      isAd: true,
      offers: [],
    },
  ],
  recommendedProductLinks: [
    {
      id: 3001,
      marketName: "danawa",
      marketProductNo: "mock-related-1",
      marketItemNo: null,
      mallCode: null,
      mallName: null,
      linkType: "DANAWA_CATALOG",
      relationKind: "RECOMMENDED_PRODUCT",
      searchKeyword: "식기세척기 주방세제 미니 캡슐 50개입",
      sourceUrl: "https://search.danawa.com/dsearch.php?query=식기세척기 주방세제 미니 캡슐 50개입",
      name: "식기세척기 주방세제 미니 캡슐형 50개입",
      imageUrl: null,
      price: 13900,
      isCatalog: true,
      categoryName: "식기세척기 세제",
      mallCount: 9,
      reviewCount: 87,
      rating: 4.6,
      summary: "미니 캡슐형, 50개입, 식기세척기 전용",
      recommendationScore: 92,
      recommendationTier: "PRIMARY",
      recommendationReasons: ["동일 카테고리", "동일 입수 50개", "다른 브랜드"],
      listingOrder: 1,
      isAd: false,
      offers: [],
    },
    {
      id: 3002,
      marketName: "danawa",
      marketProductNo: "mock-related-2",
      marketItemNo: null,
      mallCode: null,
      mallName: null,
      linkType: "DANAWA_CATALOG",
      relationKind: "RECOMMENDED_PRODUCT",
      searchKeyword: "식기세척기 세제 캡슐 레몬향 50개입",
      sourceUrl: "https://search.danawa.com/dsearch.php?query=식기세척기 세제 캡슐 레몬향 50개입",
      name: "레몬향 식기세척기 세제 캡슐 50개입",
      imageUrl: null,
      price: 12900,
      isCatalog: true,
      categoryName: "식기세척기 세제",
      mallCount: 7,
      reviewCount: 63,
      rating: 4.4,
      summary: "레몬향 캡슐형 식기세척기 세제",
      recommendationScore: 88,
      recommendationTier: "PRIMARY",
      recommendationReasons: ["동일 카테고리", "동일 입수 50개", "다른 브랜드"],
      listingOrder: 2,
      isAd: false,
      offers: [],
    },
  ],
  otherUserInterestProducts: [
    {
      id: 9001,
      displayName: "식기세척기 주방세제 미니 캡슐형 50개입",
      brand: null,
      summary: "다른 사용자가 자주 저장한 미니 캡슐형 식기세척기 세제입니다.",
      interestCount: 7,
      sourceProduct: {
        id: 900101,
        marketName: "danawa",
        marketProductNo: "mock-user-interest-1",
        sourceUrl:
          "https://search.danawa.com/dsearch.php?query=식기세척기 주방세제 미니 캡슐 50개입",
        name: "식기세척기 주방세제 미니 캡슐형 50개입",
        imageUrl: "",
        price: 13900,
      },
      updatedAt: now,
    },
    {
      id: 9002,
      displayName: "레몬향 식기세척기 세제 캡슐 50개입",
      brand: null,
      summary: "브랜드보다 용도와 용량이 비슷한 관심 상품입니다.",
      interestCount: 4,
      sourceProduct: {
        id: 900201,
        marketName: "danawa",
        marketProductNo: "mock-user-interest-2",
        sourceUrl: "https://search.danawa.com/dsearch.php?query=식기세척기 세제 캡슐 레몬향 50개입",
        name: "레몬향 식기세척기 세제 캡슐 50개입",
        imageUrl: "",
        price: 12900,
      },
      updatedAt: now,
    },
  ],
  createdAt: now,
  updatedAt: now,
};

export const MOCK_SAVED_PRODUCT_PAGE: SavedProductListPage = {
  products: [MOCK_SAVED_PRODUCT],
  page: 1,
  pageSize: 10,
  totalCount: 1,
  totalPages: 1,
  hasNextPage: false,
  hasPreviousPage: false,
};

export function withMockSavedProductFallback(page: SavedProductListPage) {
  return page.products.length > 0 ? page : MOCK_SAVED_PRODUCT_PAGE;
}
