/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMarketsRouteImport } from './routes/api/markets'
import { Route as ApiProductsIndexRouteImport } from './routes/api/products/index'
import { Route as ApiScrapeTargetsRouteImport } from './routes/api/scrape/targets'
import { Route as ApiScrapeParseRouteImport } from './routes/api/scrape/parse'
import { Route as ApiProductsAnalyzeRouteImport } from './routes/api/products/analyze'
import { Route as ApiInternalProductsRouteImport } from './routes/api/internal/products'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketsRoute = ApiMarketsRouteImport.update({
  id: '/api/markets',
  path: '/api/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsIndexRoute = ApiProductsIndexRouteImport.update({
  id: '/api/products/',
  path: '/api/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScrapeTargetsRoute = ApiScrapeTargetsRouteImport.update({
  id: '/api/scrape/targets',
  path: '/api/scrape/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScrapeParseRoute = ApiScrapeParseRouteImport.update({
  id: '/api/scrape/parse',
  path: '/api/scrape/parse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsAnalyzeRoute = ApiProductsAnalyzeRouteImport.update({
  id: '/api/products/analyze',
  path: '/api/products/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalProductsRoute = ApiInternalProductsRouteImport.update({
  id: '/api/internal/products',
  path: '/api/internal/products',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/markets': typeof ApiMarketsRoute
  '/api/internal/products': typeof ApiInternalProductsRoute
  '/api/products/analyze': typeof ApiProductsAnalyzeRoute
  '/api/scrape/parse': typeof ApiScrapeParseRoute
  '/api/scrape/targets': typeof ApiScrapeTargetsRoute
  '/api/products/': typeof ApiProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/markets': typeof ApiMarketsRoute
  '/api/internal/products': typeof ApiInternalProductsRoute
  '/api/products/analyze': typeof ApiProductsAnalyzeRoute
  '/api/scrape/parse': typeof ApiScrapeParseRoute
  '/api/scrape/targets': typeof ApiScrapeTargetsRoute
  '/api/products': typeof ApiProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/markets': typeof ApiMarketsRoute
  '/api/internal/products': typeof ApiInternalProductsRoute
  '/api/products/analyze': typeof ApiProductsAnalyzeRoute
  '/api/scrape/parse': typeof ApiScrapeParseRoute
  '/api/scrape/targets': typeof ApiScrapeTargetsRoute
  '/api/products/': typeof ApiProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/markets'
    | '/api/internal/products'
    | '/api/products/analyze'
    | '/api/scrape/parse'
    | '/api/scrape/targets'
    | '/api/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/markets'
    | '/api/internal/products'
    | '/api/products/analyze'
    | '/api/scrape/parse'
    | '/api/scrape/targets'
    | '/api/products'
  id:
    | '__root__'
    | '/'
    | '/api/markets'
    | '/api/internal/products'
    | '/api/products/analyze'
    | '/api/scrape/parse'
    | '/api/scrape/targets'
    | '/api/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiMarketsRoute: typeof ApiMarketsRoute
  ApiInternalProductsRoute: typeof ApiInternalProductsRoute
  ApiProductsAnalyzeRoute: typeof ApiProductsAnalyzeRoute
  ApiScrapeParseRoute: typeof ApiScrapeParseRoute
  ApiScrapeTargetsRoute: typeof ApiScrapeTargetsRoute
  ApiProductsIndexRoute: typeof ApiProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/markets': {
      id: '/api/markets'
      path: '/api/markets'
      fullPath: '/api/markets'
      preLoaderRoute: typeof ApiMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/': {
      id: '/api/products/'
      path: '/api/products'
      fullPath: '/api/products/'
      preLoaderRoute: typeof ApiProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scrape/targets': {
      id: '/api/scrape/targets'
      path: '/api/scrape/targets'
      fullPath: '/api/scrape/targets'
      preLoaderRoute: typeof ApiScrapeTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scrape/parse': {
      id: '/api/scrape/parse'
      path: '/api/scrape/parse'
      fullPath: '/api/scrape/parse'
      preLoaderRoute: typeof ApiScrapeParseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/analyze': {
      id: '/api/products/analyze'
      path: '/api/products/analyze'
      fullPath: '/api/products/analyze'
      preLoaderRoute: typeof ApiProductsAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/products': {
      id: '/api/internal/products'
      path: '/api/internal/products'
      fullPath: '/api/internal/products'
      preLoaderRoute: typeof ApiInternalProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiMarketsRoute: ApiMarketsRoute,
  ApiInternalProductsRoute: ApiInternalProductsRoute,
  ApiProductsAnalyzeRoute: ApiProductsAnalyzeRoute,
  ApiScrapeParseRoute: ApiScrapeParseRoute,
  ApiScrapeTargetsRoute: ApiScrapeTargetsRoute,
  ApiProductsIndexRoute: ApiProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
