/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMarketsRouteImport } from './routes/api/markets'
import { Route as ApiScrapeTargetsRouteImport } from './routes/api/scrape/targets'
import { Route as ApiScrapeParseRouteImport } from './routes/api/scrape/parse'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketsRoute = ApiMarketsRouteImport.update({
  id: '/api/markets',
  path: '/api/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScrapeTargetsRoute = ApiScrapeTargetsRouteImport.update({
  id: '/api/scrape/targets',
  path: '/api/scrape/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScrapeParseRoute = ApiScrapeParseRouteImport.update({
  id: '/api/scrape/parse',
  path: '/api/scrape/parse',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/markets': typeof ApiMarketsRoute
  '/api/scrape/parse': typeof ApiScrapeParseRoute
  '/api/scrape/targets': typeof ApiScrapeTargetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/markets': typeof ApiMarketsRoute
  '/api/scrape/parse': typeof ApiScrapeParseRoute
  '/api/scrape/targets': typeof ApiScrapeTargetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/markets': typeof ApiMarketsRoute
  '/api/scrape/parse': typeof ApiScrapeParseRoute
  '/api/scrape/targets': typeof ApiScrapeTargetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/markets' | '/api/scrape/parse' | '/api/scrape/targets'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/markets' | '/api/scrape/parse' | '/api/scrape/targets'
  id:
    | '__root__'
    | '/'
    | '/api/markets'
    | '/api/scrape/parse'
    | '/api/scrape/targets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiMarketsRoute: typeof ApiMarketsRoute
  ApiScrapeParseRoute: typeof ApiScrapeParseRoute
  ApiScrapeTargetsRoute: typeof ApiScrapeTargetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/markets': {
      id: '/api/markets'
      path: '/api/markets'
      fullPath: '/api/markets'
      preLoaderRoute: typeof ApiMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scrape/targets': {
      id: '/api/scrape/targets'
      path: '/api/scrape/targets'
      fullPath: '/api/scrape/targets'
      preLoaderRoute: typeof ApiScrapeTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scrape/parse': {
      id: '/api/scrape/parse'
      path: '/api/scrape/parse'
      fullPath: '/api/scrape/parse'
      preLoaderRoute: typeof ApiScrapeParseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiMarketsRoute: ApiMarketsRoute,
  ApiScrapeParseRoute: ApiScrapeParseRoute,
  ApiScrapeTargetsRoute: ApiScrapeTargetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
